name: symfony5-app
recipe: symfony
config:
  webroot: public

services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - symfony5.symfony5app.internal
  symfony2:
    type: mariadb
    portforward: true
    creds:
      user: symfony5
      password: symfony5
      database: symfony5
